version: "3.8"

services:
  springboot-restful-webservices:
    container_name: springboot-mensajeria
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
